### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by philwhiteuk** [bodar/totallylazy.js#29]
Since `0.464.306` the `FlexibleMoneyParser.parseAll` method throws an error when given `undefined` as an input.

```
TypeError: Cannot read properties of undefined (reading 'replace')
    at removeUnicodeMarkers (src/characters.ts:128:18)
    at _FlexibleMoneyParser.parseAll (src/money/flexible-parsing.ts:55:40)
    at Context.<anonymous> (money/money/flexible-parsing.test.ts:99:35)
    at processImmediate (node:internal/timers:464:21)
```

**Comment by philwhiteuk** [comment]
An example test case to replicate the issue:

```typescript
it(`handles bad inputs`, function () {
    expect(() => flexibleMoneyParser('en').parse(undefined as any)).to.throw();
    assert.deepEqual(flexibleMoneyParser('en').parseAll(undefined as any), []);
    assert.deepEqual(flexibleMoneyParser('en').parseAll(0.1 as any), []);
});
```
